### ISSUE TITLE
Add pgcenter

### ISSUE THREAD

**Issue by lesovsky** [mgramin/awesome-db-tools#113]
Hi, pgcenter is the CLI admin tool for observing and troubleshooting Postgres.
https://github.com/lesovsky/pgcenter
https://pgcenter.org

**Comment by mgramin** [comment]
Hi, thanks for your awesome db-tool. pgcenter is already on the this list https://github.com/mgramin/awesome-db-tools#cli-tools

**Comment by lesovsky** [comment]
yes, my mistake)) I've seen `pgstats` and supposed that pgcenter should be there.
