### ISSUE TITLE
Add: AliaSQL

### ISSUE THREAD

**Issue by DanKaLeo** [mgramin/awesome-db-tools#155]
- [https://github.com/ClearMeasure/AliaSQL](AliaSQL) - AliaSQL is a command line tool for database deployments

**Comment by mgramin** [comment]
Hi! Thanks for your issue. This project looks very old, last update in 2016

**Comment by mgramin** [comment]
Thanks for the issue, but I am closing it because AliaSQL repo seems to be abandoned
