### ISSUE TITLE
Add Cybertec PostgreSQL Configurator

### ISSUE THREAD

**Issue by mgramin** [mgramin/awesome-db-tools#48]

**Comment by LorenzHenk** [comment]
The URL has changed to https://pgconfigurator.cybertec-postgresql.com/

**Comment by LorenzHenk** [comment]
Should this be put into https://github.com/mgramin/awesome-db-tools#code-generation-tools?

**Comment by mgramin** [comment]
I assumed to place it in a new group, e.g. "Configuration tuning".

**Comment by LorenzHenk** [comment]
Great, I'll create a PR!

**Comment by mgramin** [comment]
Thanks.
